modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
issueTrackerURL="https://github.com/TJT01/Sprinkle/issues" #optional

license = "MIT License"
[[mods]] #mandatory
modId="sprinkle" #mandatory
version="1.18.2-0.3.0-alpha" #mandatory
displayName="Sprinkle" #mandatory
# updateJSONURL="http://myurl.me/" #optional
displayURL="https://github.com/TJT01/Sprinkle"
logoFile="sprinkle-logo.png" #optional
logoBlur=false
# credits="Thanks for this example mod goes to Java"
authors="TJT01" #optional
description='''
Work-in-progress mod for Minecraft 1.18.2
'''
[[dependencies.sprinkle]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40.2.0,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.sprinkle]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sprinkle]]
    modId="lapislib"
    mandatory=true
    versionRange="[1.2.0a,)"
    ordering="NONE"
    side="BOTH"
